name: Check:Quality Gates

on:
  workflow_dispatch:
  pull_request:
    branches: [main] # Or your main branch name

env:
  NX_DISABLE_DB: true

jobs:
  quality_checks_build_affected:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper linting and formatting

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or dependency of the PRD / DEV runner
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run Lint
        run: npm run lint

      - name: Build Affected apps
        run: npm run build:affected
